spring:
  datasource:
    url: jdbc:mysql://localhost:3306/watermelon?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    schema:
      - classpath:sql/init/*.sql
    initialization-mode: always

  thymeleaf:
    cache: false
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html

logging:
  file: log/app.log
  file.max-history: 30

  level:
    root: WARN
    org.springfromwork.web: INFO

